### ISSUE TITLE
how do I use the extension?

### ISSUE THREAD

**Issue by vdeppe** [bpmn-io/bpmn-js-task-priorities#3]
I tried to use the Extension, but I Always get the message: SCRIPT5009: SCRIPT5009: 'require' is not defined. Could you provide a step by step walkthrough? This would be very helpful

**Comment by nikku** [comment]
You need a proper development setup to consume the extension.

Cf. https://forum.bpmn.io/t/help-with-using-the-modeler-javascript-error-require-not-defined/177.
